export const REQUEST_MOVIES = 'REQUEST_MOVIES';
export const REQUEST_MOVIES_SUCCESS = 'REQUEST_MOVIES_SUCCESS';
export const REQUEST_MOVIES_FAIL = 'REQUEST_MOVIES_FAIL';

export const REQUEST_MOVIE = 'REQUEST_MOVIE';
export const REQUEST_MOVIE_SUCCESS = 'REQUEST_MOVIE_SUCCESS';
export const REQUEST_MOVIE_FAIL = 'REQUEST_MOVIE_FAIL';

export const UPDATE_MOVIE = 'UPDATE_MOVIE';
export const CREATE_MOVIE = 'CREATE_MOVIE';
export const DELETE_MOVIE = 'DELETE_MOVIE';
